name: Build jsc-android and publish

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    container: reactnativecommunity/react-native-android:5.4

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: 🔨 Use JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Install packages
        run: |
          apt-get update
          apt-get install coreutils curl git subversion wget python3 ruby gperf -y
          wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          echo 'export NVM_DIR="$HOME/.nvm"' >> "${HOME}/.bashrc"
          echo '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm' >> "${HOME}/.bashrc"
          source "${HOME}/.bashrc"
          nvm install 16
          nvm use 16
          nvm alias default 16
        shell: bash

      - name: Install Android packages
        run: |
          sdkmanager \
            "cmake;3.10.2.4988404" \
            "cmake;3.18.1" \
            "ndk;23.2.8568313"
          # move out builtin icu headers from ndk and prevent icu build errors
          mv "${ANDROID_HOME}/ndk/23.2.8568313/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/unicode" "${ANDROID_HOME}/ndk/23.2.8568313/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/unicode2"
          echo "ANDROID_NDK=$ANDROID_HOME/ndk/23.2.8568313" >> $GITHUB_ENV
        shell: bash

      - name: Build
        run: |
          yarn clean
          yarn download
          yarn start
        shell: bash

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn publish --access public
